
# Our log file
log_file: ihb.log
# debug or info
log_level: debug

# Default host is the default ip address of the currnet host
# If you have multiple interfaces you can set which one
# Otherwise don't define it.
host: 
# Default port is 8088 for the local REST interface
#port: 8088

isy:
  host: your_isy_host_or_ip_address
  port: your_isy_port_usually_80
  user: your_isy_user_name
  password: diabl099
  # Set to true or false for logging isy activity
  log_enable: true

# HABridge info
# TODO: Should make the default the current host.
# port must be 80 for Google Home!
#      can be anything for Alexa
bridge:
  host: your_ha_bridge_host
  port: your_ha_bridge_port

