
# The log file.
log_file: logs/ihab.log
# debug or info
log_level: debug

# Default host is the default ip address of the curreet host
# If you have multiple interfaces you can set which one
# Otherwise don't define it.
host: 
# Default port is 8088 for the local REST interface
#port: 8088

#
# Settings for your ISY
#
isy:
  host: your_isy_host_or_ip_address
  port: 80
  user: your_isy_user_name
  password: your_isy_password
  log_enable: false

#
# Settings for your ha-bridge
# Default host is the current host, and port is 80
#
bridge:
  host: 
  port: 
